# Generated by Django 4.2.2 on 2023-06-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newbankmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('uname', models.CharField(max_length=50)),
                ('emailfield', models.EmailField(max_length=254)),
                ('phonenum', models.IntegerField()),
                ('fileimage', models.FileField(upload_to='bankapp/static')),
                ('pinone', models.CharField(max_length=30)),
            ],
        ),
    ]
