# Generated by Django 4.2.2 on 2023-07-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_newbankmodel_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='newbankmodel',
            name='ac_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
