# Generated by Django 4.2.2 on 2023-07-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0006_notimodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='addamountmodel',
            name='uid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
