# Generated by Django 4.2.2 on 2023-07-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0008_withdrawamount_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicnew', models.CharField(max_length=50)),
                ('textar', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
